version: '3.8'

x-python-containers: &python-containers
  build:
    context: .
    dockerfile: ./deploy/Dockerfile
  volumes:
    - .:/app
  env_file:
    - .env.dev

services:
  web:
    <<: *python-containers
    command: /app/deploy/start-django-app.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev

  redis:
    image: redis:7

  celery-worker:
    <<: *python-containers
    command: /app/deploy/start-celery-worker.sh
    depends_on:
      - db
      - redis
    env_file:
      - .env.dev

  celery-beat:
    <<: *python-containers
    command: /app/deploy/start-celery-beat.sh
    depends_on:
      - db
      - redis
    env_file:
      - .env.dev

  autotests:
    <<: *python-containers
    command: bash -c "coverage run manage.py test && coverage report"
    depends_on:
      - db
    environment:
      TESTING: 1

volumes:
  postgres_data: