# Generated by Django 4.2.4 on 2023-09-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='char_code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='currencyprice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='currencyprice',
            unique_together={('date', 'currency')},
        ),
    ]
