# Generated by Django 4.2.4 on 2023-09-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_rename_threshold_price_usercurrency_threshold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('char_code',)},
        ),
        migrations.AlterModelOptions(
            name='currencyprice',
            options={'ordering': ('-date', 'currency')},
        ),
        migrations.AlterModelOptions(
            name='usercurrency',
            options={'ordering': ('currency',)},
        ),
    ]
