# Generated by Django 4.2.4 on 2023-09-06 20:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0006_alter_currency_options_alter_currencyprice_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercurrency',
            unique_together={('user', 'currency')},
        ),
    ]
