# Generated by Django 4.2.4 on 2023-09-06 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_alter_usercurrency_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_email_latest_date', models.DateField(default=datetime.date(2000, 1, 1))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
